[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install" # This line explicitly tells Netlify to run npm install

# Remove or comment out the [[plugins]] section if it's there
# [[plugins]]
# package = "@netlify/plugin-functions-install-core"